/*
 * This source file was generated by the Gradle 'init' task
 */
package esporthub;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appInstantiates() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest, "app should instantiate successfully");
    }
}
